config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do
    get 'my_students', on: :collection
  end
  devise_for :users

  root to: 'home#index'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'activity', to: 'home#activity'

  resources :users, only: %i[index edit update show]
  resources :courses do
    get 'purchased', 'pending_review', 'created', on: :collection
    resources :enrollments, only: %i[new create]
    resources :lessons
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course, counter_cache: true
  # User.find_each {|user| User.reset_counters(user.id, :enrollments)}
  belongs_to :user, counter_cache: true

  extend FriendlyId
  friendly_id :to_s, use: :slugged

  validates :user, :course, presence: true
  validates :rating, presence: true, on: :update
  validates :review, presence: true, on: :update
  validates :user_id, uniqueness: { scope: :course_id }
  validates :course_id, uniqueness: { scope: :user_id }

  validate :cant_subscribe_to_own_course  # user can't create a subscription if course.user == current_user.id

  scope :pending_review, -> { where(rating: [0, nil, ''], review: [0, nil, '']) }
  scope :reviewed, -> { where.not(review: [0, nil, ""]) }
  scope :latest_reviews, -> { limit(3).order(rating: :desc, created_at: :desc) }


  def to_s
    user.to_s + ' ' + course.to_s
  end

  after_save do
    unless rating.nil? || rating.zero?
      course.update_rating
    end
  end

  after_destroy do
    course.update_rating
  end

  protected

  def cant_subscribe_to_own_course
    if new_record? && user_id.present? && (user_id == course.user_id)
      errors.add(:base, 'You can not subscribe to your own course')
    end
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[show edit update destroy]
  before_action :set_course, only: %i[new create]

  def index
    @ransack_path = enrollments_path

    @q = Enrollment.ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    authorize @enrollments
  end

  def my_students
    @ransack_path = my_students_enrollments_path

    @q = Enrollment.joins(:course).where(courses: {user: current_user}).ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    render 'index'
  end

  def show; end

  def new
    @enrollment = Enrollment.new
  end

  def edit
    authorize @enrollment
  end

  def create
    # if @course.price > 0
    #   flash[:alert] = "You can not access paid courses yet."
    #   redirect_to new_course_enrollment_path(@course)
    # else
    @enrollment = current_user.buy_course(@course)

    redirect_to course_path(@course), notice: 'You are enrolled!'
    # end
    # @enrollment = Enrollment.new(enrollment_params)
    # @enrollment.price = @enrollment.course.price

    # respond_to do |format|
    #   if @enrollment.save
    #     format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully created." }
    #     format.json { render :show, status: :created, location: @enrollment }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @enrollment.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def update
    authorize @enrollment

    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollment_url(@enrollment), notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @enrollment
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_course
    @course = Course.friendly.find(params[:course_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_enrollment
    @enrollment = Enrollment.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def enrollment_params
    # params.require(:enrollment).permit(:course_id, :user_id, :rating, :review, :price)
    params.require(:enrollment).permit(:rating, :review)
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.erb
<div class="card mb-4">
  <div class="card-header">
    <div class="fa fa-user">
    </div>
    <%= link_to enrollment.user.username, user_path(enrollment.user) %>
    <div class="fa fa-clock">
    </div>
    <%= time_ago_in_words(enrollment.updated_at) %>
    <div class="fa fa-graduation-cap">
    </div>
    <%= link_to enrollment.course, course_path(enrollment.course) %>
  </div>
  <div class="card-body">
    <div class="fa fa-star text-warning"></div>
    <%= enrollment.rating %>
    <div class="fa fa-comment small"> <%= enrollment.review %></div>
  </div>
  <% if current_user %>
    <div class="card-footer">
      <% if policy(enrollment).edit? %>
        <%= link_to "Edit Review", edit_enrollment_path(enrollment) %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/enrollments/_form.html.erb
<%= simple_form_for(@enrollment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :rating, collection: 1..5, as: :radio_buttons %>
    <%= f.input :review %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<div class="card mb-4">
  <div class="card-header">
    <h1>Editing Enrollment</h1>
  </div>
  <div class="card-body">
    <%= render 'form', enrollment: @enrollment %>
  </div>
  <div class="card-footer">
    <%= link_to 'Show', @enrollment %> |
    <%= link_to 'Back', enrollments_path %>
  </div>
</div>

app/views/enrollments/index.html.erb
<p id="notice"><%= notice %></p>
<%= search_form_for @q, url: @ransack_path do |f| %>
  <%= f.search_field :course_title_cont, placeholder: 'title' %>
  <%= f.search_field :review_cont, placeholder: 'review' %>
  <%= f.search_field :user_email_cont, placeholder: 'email' %>
  <%= f.search_field :rating_eq, placeholder: 'rating' %>

  <%= f.submit %>
<% end %>
<br/>

<%= link_to @ransack_path, class: "btn btn-sm btn-secondary" do %>
  <i class="fa-solid fa-rotate"></i>
<% end %>
<br/>

<h3>
  <div class="text-center">
    <%= action_name.humanize %> Enrollments
    <div class="badge badge-info">
      <%= @enrollments.count %>
    </div>
  </div>
</h3>
<h1>Enrollments</h1>

<div class="table-responsive">
  <table class="table table-bordered table-striped table-sm">
    <thead>
      <tr>
        <th>
          <%= sort_link(@q, :id) %>
        </th>
        <th><%= sort_link(@q, :user_email) %></th>
        <th><div class="fa fa-graduation-cap"> <%= sort_link(@q, :course_title) %></th>
        <th><div class="fa fa-clock"></div> <div class="fa fa-lock-open"></div></th>
        <th><div class="fa fa-dollar-sign"></div> <%= sort_link(@q, :price) %></th>
        <th>
          <div class="fa fa-clock text-warning"></div>
          <%= sort_link(@q, :updated_at) %>
        </th>
        <th>
          <div class="fa fa-star text-warning"></div>
          <%= sort_link(@q, :rating) %>
        </th>
        <th>
          <div class="fa fa-comment text-warning"></div>
          <%= sort_link(@q, :review) %>
        </th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @enrollments.each do |enrollment| %>
        <tr>
          <td><%= enrollment.course_id %></td>
          <td><%= link_to enrollment.user, user_path(enrollment.user) %></td>
          <td><%= link_to enrollment.course, course_path(enrollment.course) %></td>
          <td><%= enrollment.created_at.strftime("%d/%b/%y") %></td>
          <td><%= number_to_currency(enrollment.price) %></td>
          <td>
            <% if enrollment.rating.present? %>
              <%= enrollment.updated_at.strftime("%d/%b/%y - %H:%M:%S") %>
            <% end %>
          </td>
          <td><%= enrollment.rating %></td>
          <td><%= enrollment.review %></td>
          <td><%= link_to 'See Review', enrollment %></td>
          <td><%= link_to 'Add Review', edit_enrollment_path(enrollment) %></td>
          <td><%= link_to 'Delete Enrollment', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%== pagy_bootstrap_nav(@pagy) %>
  <%== pagy_bootstrap_nav_js(@pagy) %>
</div>

<br>

<%= link_to 'New Enrollment', new_enrollment_path %>

app/views/enrollments/new.html.erb
<div class="card mb-4">
  <div class="card-header">
    <h1>
      <div class="fa fa-graduation-cap"></div>
      <%= link_to @course.title, course_path(@course) %>
      <br/>
      <br/>
      <hr/>
      <br/>
      <div class="fa fa-lock-open"></div>
      Buy Course
    </h1>
  </div>
  <div class="card-body">
    <%= form_tag course_enrollments_path(@course) do %>
      <%= submit_tag "Pay #{@course.price}", class: "btn btn-success" %>
    <% end %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', course_path(@course) %>
  </div>
</div>

app/views/enrollments/show.html.erb
<%= render 'enrollments/enrollment', enrollment: @enrollment %>