config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do
    get 'my_students', on: :collection
  end
  devise_for :users

  root to: 'home#index'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'activity', to: 'home#activity'

  resources :users, only: %i[index edit update show]
  resources :courses do
    get 'purchased', 'pending_review', 'created', on: :collection
    resources :enrollments, only: %i[new create]
    resources :lessons
  end
end

app/views/layouts/_footer.html.erb
<div class="footer bg-light p-5">
  <div class="continer">
    <div class="row">
      <div class="col-md-4">
        Copyright
        ©
        <%= Time.now.year %>
        CoursePlatform Sp. z o.o.
        <div class="row">
          <div class="fa.fa-envelope"></div>
          <%= mail_to 'yashm@outlook.com' %>
        </div>
      </div>
      <div class="col-md-4">
         Privacy policy
        <div class="row">
          Terms and conditions
        </div>
      </div>
      <div class="col-md-4">
        About us
        <div class="row">
          <%= link_to 'Teach on CoursePlatform', new_course_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Rubygems</a>
  <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if current_user %>
      <ul class="navbar-nav mr-auto">
        <li class="<%= 'active font-weight-bold' if current_page?(root_path) %> nav-item">
          <%= link_to root_path, class: 'nav-link' do %>
            <div class="fa fa-home"></div>
            Home
          <% end %>
        </li>
        <li class="<%= 'active font-weight-bold' if current_page?(courses_path) %> nav-item">
          <%= link_to courses_path, class: 'nav-link' do %>
            <div class="fa fa-graduation-cap"></div>
            Courses
          <% end %>
        </li>
        <% if current_user.has_role?(:student)%>
          <li class="nav-item dropdown">
            <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="studentDropdown" role="button">
              <b>
                <div class="fa fa-graduation-cap"></div>
                Learn
              </b>
            </a>
            <div aria-labelledby="studentDropdown" class="dropdown-menu dropdown-menu-right">
              <%= link_to purchased_courses_path, class: "dropdown-item" do %>
                <div class="fa fa-graduation-cap"></div>
                <b>
                  Purchased Courses
                  <div class="badge badge-danger">
                    <%= current_user.enrollments_count %>
                  </div>
                </b>
              <% end %>
              <%= link_to pending_review_courses_path, class: "dropdown-item" do %>
                <div class="fa fa-star"></div>
                <b>
                 Pending Reviews
                 <div class="badge badge-danger">
                    <%= current_user.enrollments.pending_review.count %>
                  </div>
                </b>
              <% end %>
            </div>
          </li>
        <% end %>
        <% if current_user.has_role?(:teacher)%>
          <li class="nav-item dropdown">
            <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="teacherDropdown" role="button">
              <b>
                <div class="fa fa-person-chalkboard"></div>
                Teach
              </b>
            </a>
            <div aria-labelledby="teacherDropdown" class="dropdown-menu dropdown-menu-right">
              <%= link_to new_course_path, class: "dropdown-item" do %>
                <div class="fa fa-plus"></div>
                <b>New Course</b>
              <% end %>
              <%= link_to created_courses_path, class: "dropdown-item" do %>
                <div class="fa fa-graduation-cap"></div>
                <b>My Courses</b>
                <div class="badge badge-danger">
                  <%= current_user.courses_count %>
                </div>
              <% end %>
              <%= link_to my_students_enrollments_path, class: "dropdown-item" do %>
                <div class="fa fa-graduation-cap"></div>
                <b>My Students</b>
                <div class="badge badge-danger">
                  <%= Enrollment.joins(:course).where(courses: {user: current_user}).count %>
                </div>
              <% end %>
            </div>
          </li>
        <% end %>
        <% if current_user.has_role?(:admin)%>
          <li class="nav-item dropdown">
            <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="adminDropdown" role="button">
              <b>
                <div class="fa fa-cog"></div>
                Admin
              </b>
            </a>
            <div aria-labelledby="adminDropdown" class="dropdown-menu dropdown-menu-right">
              <%= link_to users_path, class: "dropdown-item" do %>
                <div class="fa fa-user"></div>
                <b>Users</b>
                <div class="badge badge-danger">
                  <%= User.count %>
                </div>
              <% end %>
              <%= link_to enrollments_path, class: "dropdown-item" do %>
                <div class="fa fa-lock-open"></div>
                <b>Enrollments</b>
                <div class="badge badge-danger">
                  <%= Enrollment.count %>
                </div>
              <% end %>
              <%= link_to activity_path, class: 'dropdown-item' do %>
                <div class="fa fa-bell"></div>
                <b>Activity</b>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
        <%= search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f| %>
          <div class="input-group">
            <%= f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off %>
            <span class="input-group-append">
              <button class="btn btn-primary btn-sm" type="submit">
                <span aria-hidden="true" class="fa fa-search"></span>
              </button>
            </span>
          </div>
        <% end %>
        <ul class="navbar-nav mr-right">
          <li class="nav-item dropdown">
            <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
              <b>
                <%= current_user.email %>
              </b>
            </a>
            <div aria-labelledby="navbarDropdown" class="dropdown-menu dropdown-menu-right">
              <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                <div class="fa fa-cog"></div>
                <b>Account settings</b>
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                <div class="fa fa-sign-out-alt"></div>
                <b>Sign out</b>
              <% end %>
            </div>
          </li>
        </ul>
    <% else %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<div>
  <% flash.each do |type, msg| %>
    <% if type == "notice" %>
      <div class="alert alert-success">
    <% elsif type == "alert" %>
      <div class="alert alert-danger">
    <% else %>
      <div class='alert alert-<%= "#{type}" %>'>
    <% end %>
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= msg %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ELearningPlatform</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="trix-content">
      <%= render 'layouts/header' %>
      <%= render 'layouts/messages' %>
      <div class="container-fluid">
        <br />
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>